name: c_mbrl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ffmpeg
  - pip
  - pip:
    - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - jax[cuda11_pip]==0.4.20
    - jaxlib[cuda11_pip]==0.4.20
    - carl-bench[brax,dm_control]@git+https://github.com/automl/CARL.git@f4b51b6cfc39b1dea4600750dc52bfae1de50186
    - ipykernel
    - protobuf==3.20
    - ruamel.yaml==0.17.32
    - brax==0.9.3
    - -e ./dreamerv3_compat
    - wandb
    - moviepy
    - imageio
    - jsonlines
    - --editable .