name: c_mbrl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ffmpeg
  - pip
  - pip:
    - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - jax[cuda11_pip]==0.4.20
    - jaxlib[cuda11_pip]==0.4.20
    - carl-bench[brax,dm_control]@git+https://github.com/automl/CARL.git@afbd479a155b0bf6be21c38fd894202593d624ff
    - ipykernel
    - protobuf==3.20
    - ruamel.yaml==0.17.32
    - brax==0.9.3
    - dreamerv3@git+https://github.com/Kinds-of-Intelligence-CFI/dreamerv3-compat.git@85be05b
    - wandb
    - moviepy
    - imageio
    - jsonlines
    - --editable .